services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile   # köke göre doğru yol
        container_name: myapp-php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html                  # kökü mount et
        depends_on:
            - mysql

    nginx:
        image: nginx:stable
        container_name: myapp-nginx
        ports:
            - "80:80"                           # 80 doluysa "8080:80" yap
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: myapp-mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"                       # Mac’te MySQL çalışıyorsa "13306:3306" yap

    redis:
        image: redis:alpine
        container_name: myapp-redis
        ports:
            - "6379:6379"

volumes:
    dbdata:
